spring:
  rabbitmq:
    hostname: localhost
    username: guest
    password: guest
    exchangeName: bankingexchange
    queueName: banking
  application:
    database: banking
    eventsCollectionName: events
    snapshotCollectionName: snapshots
server:
  port: 9000
message: Hello world
